package CamNecT.server.global.storage.model;

public enum UploadPurpose {
    COMMUNITY_POST_ATTACHMENT,
    PORTFOLIO_ATTACHMENT,
    PORTFOLIO_THUMBNAIL,
    ACTIVITY_ATTACHMENT,
    ACTIVITY_THUMBNAIL,
    VERIFICATION_DOCUMENT,
    PROFILE_IMAGE,
    REPORT_EVIDENCE
}
